version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=nico
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5432:5432
    #para agregar persistencia al contenedor y se guarde la data cuando se baje el servicio
    volumes: 
     -  ./postgres_data:/var/lib/postgresql/data